/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CWBountyPool {
  export type BountyStruct = {
    funder: AddressLike;
    amount: BigNumberish;
    diseaseTag: string;
    criteria: string;
    deadline: BigNumberish;
    status: BigNumberish;
    claimCount: BigNumberish;
  };

  export type BountyStructOutput = [
    funder: string,
    amount: bigint,
    diseaseTag: string,
    criteria: string,
    deadline: bigint,
    status: bigint,
    claimCount: bigint
  ] & {
    funder: string;
    amount: bigint;
    diseaseTag: string;
    criteria: string;
    deadline: bigint;
    status: bigint;
    claimCount: bigint;
  };

  export type ClaimStruct = {
    scientist: AddressLike;
    roId: string;
    justification: string;
    status: BigNumberish;
    shareBps: BigNumberish;
  };

  export type ClaimStructOutput = [
    scientist: string,
    roId: string,
    justification: string,
    status: bigint,
    shareBps: bigint
  ] & {
    scientist: string;
    roId: string;
    justification: string;
    status: bigint;
    shareBps: bigint;
  };

  export type EscrowStruct = {
    amount: BigNumberish;
    scientist: AddressLike;
    institutionName: string;
    createdAt: BigNumberish;
    claimed: boolean;
  };

  export type EscrowStructOutput = [
    amount: bigint,
    scientist: string,
    institutionName: string,
    createdAt: bigint,
    claimed: boolean
  ] & {
    amount: bigint;
    scientist: string;
    institutionName: string;
    createdAt: bigint;
    claimed: boolean;
  };

  export type ScientistProfileStruct = {
    institutionName: string;
    institutionSplitBps: BigNumberish;
    institutionWallet: AddressLike;
    registered: boolean;
  };

  export type ScientistProfileStructOutput = [
    institutionName: string,
    institutionSplitBps: bigint,
    institutionWallet: string,
    registered: boolean
  ] & {
    institutionName: string;
    institutionSplitBps: bigint;
    institutionWallet: string;
    registered: boolean;
  };
}

export interface CWBountyPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveClaim"
      | "bounties"
      | "cancelBounty"
      | "claimEscrow"
      | "claims"
      | "createBounty"
      | "escrowCount"
      | "escrowPeriod"
      | "escrows"
      | "finalizeBounty"
      | "getBounty"
      | "getClaim"
      | "getEscrow"
      | "getScientist"
      | "institutionWallets"
      | "nextBountyId"
      | "owner"
      | "platformFeeBps"
      | "registerInstitutionWallet"
      | "registerScientist"
      | "rejectClaim"
      | "renounceOwnership"
      | "scientists"
      | "setEscrowPeriod"
      | "setPlatformFeeBps"
      | "setTreasury"
      | "submitClaim"
      | "totalBounties"
      | "transferOwnership"
      | "treasury"
      | "withdrawExpiredEscrow"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyCancelled"
      | "BountyCreated"
      | "BountyFinalized"
      | "ClaimApproved"
      | "ClaimRejected"
      | "ClaimSubmitted"
      | "EscrowClaimed"
      | "EscrowCreated"
      | "EscrowExpiredWithdraw"
      | "InstitutionWalletRegistered"
      | "OwnershipTransferred"
      | "ScientistRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveClaim",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claims",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrowPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaim",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScientist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "institutionWallets",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBountyId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerInstitutionWallet",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerScientist",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectClaim",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scientists",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitClaim",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBounties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawExpiredEscrow",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getScientist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "institutionWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextBountyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerInstitutionWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerScientist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scientists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBounties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawExpiredEscrow",
    data: BytesLike
  ): Result;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [bountyId: BigNumberish, refunded: BigNumberish];
  export type OutputTuple = [bountyId: bigint, refunded: bigint];
  export interface OutputObject {
    bountyId: bigint;
    refunded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    funder: AddressLike,
    amount: BigNumberish,
    diseaseTag: string
  ];
  export type OutputTuple = [
    bountyId: bigint,
    funder: string,
    amount: bigint,
    diseaseTag: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    funder: string;
    amount: bigint;
    diseaseTag: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyFinalizedEvent {
  export type InputTuple = [bountyId: BigNumberish, totalPaid: BigNumberish];
  export type OutputTuple = [bountyId: bigint, totalPaid: bigint];
  export interface OutputObject {
    bountyId: bigint;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimApprovedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    claimIndex: BigNumberish,
    shareBps: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    claimIndex: bigint,
    shareBps: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    claimIndex: bigint;
    shareBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimRejectedEvent {
  export type InputTuple = [bountyId: BigNumberish, claimIndex: BigNumberish];
  export type OutputTuple = [bountyId: bigint, claimIndex: bigint];
  export interface OutputObject {
    bountyId: bigint;
    claimIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimSubmittedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    claimIndex: BigNumberish,
    scientist: AddressLike,
    roId: string
  ];
  export type OutputTuple = [
    bountyId: bigint,
    claimIndex: bigint,
    scientist: string,
    roId: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    claimIndex: bigint;
    scientist: string;
    roId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowClaimedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    institutionWallet: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    institutionWallet: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    institutionWallet: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    scientist: AddressLike,
    institutionName: string,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    scientist: string,
    institutionName: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    scientist: string;
    institutionName: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowExpiredWithdrawEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    scientist: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    scientist: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    scientist: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionWalletRegisteredEvent {
  export type InputTuple = [institutionName: string, wallet: AddressLike];
  export type OutputTuple = [institutionName: string, wallet: string];
  export interface OutputObject {
    institutionName: string;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScientistRegisteredEvent {
  export type InputTuple = [
    scientist: AddressLike,
    institutionName: string,
    splitBps: BigNumberish
  ];
  export type OutputTuple = [
    scientist: string,
    institutionName: string,
    splitBps: bigint
  ];
  export interface OutputObject {
    scientist: string;
    institutionName: string;
    splitBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CWBountyPool extends BaseContract {
  connect(runner?: ContractRunner | null): CWBountyPool;
  waitForDeployment(): Promise<this>;

  interface: CWBountyPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveClaim: TypedContractMethod<
    [bountyId: BigNumberish, claimIndex: BigNumberish, shareBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, bigint, bigint] & {
        funder: string;
        amount: bigint;
        diseaseTag: string;
        criteria: string;
        deadline: bigint;
        status: bigint;
        claimCount: bigint;
      }
    ],
    "view"
  >;

  cancelBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimEscrow: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claims: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint] & {
        scientist: string;
        roId: string;
        justification: string;
        status: bigint;
        shareBps: bigint;
      }
    ],
    "view"
  >;

  createBounty: TypedContractMethod<
    [diseaseTag: string, criteria: string, deadline: BigNumberish],
    [bigint],
    "payable"
  >;

  escrowCount: TypedContractMethod<[], [bigint], "view">;

  escrowPeriod: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        amount: bigint;
        scientist: string;
        institutionName: string;
        createdAt: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  finalizeBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [CWBountyPool.BountyStructOutput],
    "view"
  >;

  getClaim: TypedContractMethod<
    [bountyId: BigNumberish, claimIndex: BigNumberish],
    [CWBountyPool.ClaimStructOutput],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [escrowId: BigNumberish],
    [CWBountyPool.EscrowStructOutput],
    "view"
  >;

  getScientist: TypedContractMethod<
    [addr: AddressLike],
    [CWBountyPool.ScientistProfileStructOutput],
    "view"
  >;

  institutionWallets: TypedContractMethod<[arg0: string], [string], "view">;

  nextBountyId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  registerInstitutionWallet: TypedContractMethod<
    [institutionName: string, wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  registerScientist: TypedContractMethod<
    [institutionName: string, institutionSplitBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectClaim: TypedContractMethod<
    [bountyId: BigNumberish, claimIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scientists: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, boolean] & {
        institutionName: string;
        institutionSplitBps: bigint;
        institutionWallet: string;
        registered: boolean;
      }
    ],
    "view"
  >;

  setEscrowPeriod: TypedContractMethod<
    [_period: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFeeBps: TypedContractMethod<
    [_bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  submitClaim: TypedContractMethod<
    [bountyId: BigNumberish, roId: string, justification: string],
    [bigint],
    "nonpayable"
  >;

  totalBounties: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  withdrawExpiredEscrow: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveClaim"
  ): TypedContractMethod<
    [bountyId: BigNumberish, claimIndex: BigNumberish, shareBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, bigint, bigint] & {
        funder: string;
        amount: bigint;
        diseaseTag: string;
        criteria: string;
        deadline: bigint;
        status: bigint;
        claimCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimEscrow"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint] & {
        scientist: string;
        roId: string;
        justification: string;
        status: bigint;
        shareBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<
    [diseaseTag: string, criteria: string, deadline: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrowPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        amount: bigint;
        scientist: string;
        institutionName: string;
        createdAt: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBounty"
  ): TypedContractMethod<
    [bountyId: BigNumberish],
    [CWBountyPool.BountyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaim"
  ): TypedContractMethod<
    [bountyId: BigNumberish, claimIndex: BigNumberish],
    [CWBountyPool.ClaimStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: BigNumberish],
    [CWBountyPool.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScientist"
  ): TypedContractMethod<
    [addr: AddressLike],
    [CWBountyPool.ScientistProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "institutionWallets"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "nextBountyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerInstitutionWallet"
  ): TypedContractMethod<
    [institutionName: string, wallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerScientist"
  ): TypedContractMethod<
    [institutionName: string, institutionSplitBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectClaim"
  ): TypedContractMethod<
    [bountyId: BigNumberish, claimIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scientists"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, boolean] & {
        institutionName: string;
        institutionSplitBps: bigint;
        institutionWallet: string;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setEscrowPeriod"
  ): TypedContractMethod<[_period: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeeBps"
  ): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitClaim"
  ): TypedContractMethod<
    [bountyId: BigNumberish, roId: string, justification: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalBounties"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawExpiredEscrow"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BountyFinalized"
  ): TypedContractEvent<
    BountyFinalizedEvent.InputTuple,
    BountyFinalizedEvent.OutputTuple,
    BountyFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimApproved"
  ): TypedContractEvent<
    ClaimApprovedEvent.InputTuple,
    ClaimApprovedEvent.OutputTuple,
    ClaimApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimRejected"
  ): TypedContractEvent<
    ClaimRejectedEvent.InputTuple,
    ClaimRejectedEvent.OutputTuple,
    ClaimRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimSubmitted"
  ): TypedContractEvent<
    ClaimSubmittedEvent.InputTuple,
    ClaimSubmittedEvent.OutputTuple,
    ClaimSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowClaimed"
  ): TypedContractEvent<
    EscrowClaimedEvent.InputTuple,
    EscrowClaimedEvent.OutputTuple,
    EscrowClaimedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowExpiredWithdraw"
  ): TypedContractEvent<
    EscrowExpiredWithdrawEvent.InputTuple,
    EscrowExpiredWithdrawEvent.OutputTuple,
    EscrowExpiredWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionWalletRegistered"
  ): TypedContractEvent<
    InstitutionWalletRegisteredEvent.InputTuple,
    InstitutionWalletRegisteredEvent.OutputTuple,
    InstitutionWalletRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ScientistRegistered"
  ): TypedContractEvent<
    ScientistRegisteredEvent.InputTuple,
    ScientistRegisteredEvent.OutputTuple,
    ScientistRegisteredEvent.OutputObject
  >;

  filters: {
    "BountyCancelled(uint256,uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyCreated(uint256,address,uint256,string)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "BountyFinalized(uint256,uint256)": TypedContractEvent<
      BountyFinalizedEvent.InputTuple,
      BountyFinalizedEvent.OutputTuple,
      BountyFinalizedEvent.OutputObject
    >;
    BountyFinalized: TypedContractEvent<
      BountyFinalizedEvent.InputTuple,
      BountyFinalizedEvent.OutputTuple,
      BountyFinalizedEvent.OutputObject
    >;

    "ClaimApproved(uint256,uint256,uint16)": TypedContractEvent<
      ClaimApprovedEvent.InputTuple,
      ClaimApprovedEvent.OutputTuple,
      ClaimApprovedEvent.OutputObject
    >;
    ClaimApproved: TypedContractEvent<
      ClaimApprovedEvent.InputTuple,
      ClaimApprovedEvent.OutputTuple,
      ClaimApprovedEvent.OutputObject
    >;

    "ClaimRejected(uint256,uint256)": TypedContractEvent<
      ClaimRejectedEvent.InputTuple,
      ClaimRejectedEvent.OutputTuple,
      ClaimRejectedEvent.OutputObject
    >;
    ClaimRejected: TypedContractEvent<
      ClaimRejectedEvent.InputTuple,
      ClaimRejectedEvent.OutputTuple,
      ClaimRejectedEvent.OutputObject
    >;

    "ClaimSubmitted(uint256,uint256,address,string)": TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;
    ClaimSubmitted: TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;

    "EscrowClaimed(uint256,address,uint256)": TypedContractEvent<
      EscrowClaimedEvent.InputTuple,
      EscrowClaimedEvent.OutputTuple,
      EscrowClaimedEvent.OutputObject
    >;
    EscrowClaimed: TypedContractEvent<
      EscrowClaimedEvent.InputTuple,
      EscrowClaimedEvent.OutputTuple,
      EscrowClaimedEvent.OutputObject
    >;

    "EscrowCreated(uint256,address,string,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowExpiredWithdraw(uint256,address,uint256)": TypedContractEvent<
      EscrowExpiredWithdrawEvent.InputTuple,
      EscrowExpiredWithdrawEvent.OutputTuple,
      EscrowExpiredWithdrawEvent.OutputObject
    >;
    EscrowExpiredWithdraw: TypedContractEvent<
      EscrowExpiredWithdrawEvent.InputTuple,
      EscrowExpiredWithdrawEvent.OutputTuple,
      EscrowExpiredWithdrawEvent.OutputObject
    >;

    "InstitutionWalletRegistered(string,address)": TypedContractEvent<
      InstitutionWalletRegisteredEvent.InputTuple,
      InstitutionWalletRegisteredEvent.OutputTuple,
      InstitutionWalletRegisteredEvent.OutputObject
    >;
    InstitutionWalletRegistered: TypedContractEvent<
      InstitutionWalletRegisteredEvent.InputTuple,
      InstitutionWalletRegisteredEvent.OutputTuple,
      InstitutionWalletRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ScientistRegistered(address,string,uint16)": TypedContractEvent<
      ScientistRegisteredEvent.InputTuple,
      ScientistRegisteredEvent.OutputTuple,
      ScientistRegisteredEvent.OutputObject
    >;
    ScientistRegistered: TypedContractEvent<
      ScientistRegisteredEvent.InputTuple,
      ScientistRegisteredEvent.OutputTuple,
      ScientistRegisteredEvent.OutputObject
    >;
  };
}
